### ISSUE TITLE
vite 版本缺少 index.html ，及运行报错

### ISSUE THREAD

**Issue by pkl-kino** [YDJ-FE/ts-react-vite_or_webpack#52]
![image](https://user-images.githubusercontent.com/13661760/153535304-e3deb541-057b-4641-8acb-8e3c2de69b30.png)
增加 index 后，scss 文件是存在的，提示错误 Internal server error: Can't find stylesheet to import 。
预计 scss 与 vite 编译需要转译特殊符号

**Comment by jackple** [comment]
https://github.com/YDJ-FE/ts-react-vite_or_webpack/pull/53

fix

感谢反馈
